version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  build:
    commands:
      - echo "Packaging backend"
      - zip -r backend-app.zip backend appspec.yml Deployment_Scripts

  post_build:
    commands:
      - echo "Uploading to S3"
      - aws s3 cp backend-app.zip s3://sandeep-devops-artifacts-jorka-2026/backend-app.zip

      - echo "Triggering CodeDeploy"
      - aws deploy create-deployment \
          --application-name backend-app \
          --deployment-group-name backend-dg \
          --s3-location bucket=sandeep-devops-artifacts-jorka-2026,key=backend-app.zip,bundleType=zip