version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing backend dependencies"
      - cd backend
      - npm install
      - cd ..

  build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - backend/**/*
    - appspec.yml
    - Deployment_Scripts/**/*